### ISSUE TITLE
Running TryGiveJob on JoyGiver_BuyStuff causes Exception

### ISSUE THREAD

**Issue by OrionFive** [tomvd/VendingMachines#2]
When Hospitality lets a guest do `BuyVendingMachineFood`, an exception is triggered:
`Could not resolve type with token 0100007f (from typeref, class/assembly Hospitality.ItemUtility, Hospitality, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)`

The type with token 0100007f is apparently Verse.SimpleCurve. But this is not used by Hospitality anywhere near where it breaks, so I assume it's somehow related to this mod since that's when the exception happens.

It happens reliably every time I have visitors (I have no vending machines built).

**Comment by tomvd** [comment]
vending machine and storefront uses methods from Hospitality.ItemUtility , but it was moved to Hospitality.Utilities.ItemUtility so I'll just update some imports and should be fixed I hope :)
